navbar:
  # 左上角导航栏配置
  blog_title: Wataame

# 首页中心打字机文字
index:
  slogan:
    enable: true
    text: Stay hungry. Stay foolish.
# 打字机动画效果
fun_features:
  typing: # 为 subtitle 添加打字机效果
    enable: true
    typeSpeed: 40 # 打印速度
    cursorChar: "_" # 游标字符
    loop: false # 是否循环播放效果

## 文章跳转方式
# index:
#   post_url_target: _self
## 隐藏文章信息
# index:
#   post_meta:
#     date: true
#     category: true
#     tag: true

# 暗色模式
dark_mode:
  enable: true
  default: auto

## 关于信息
# 介绍自己的基本信息
about:
  avatar: /images/image-info/avatar.JPG
  name: "Aaron Tang"
  intro: "Scholar"
# 社交图标
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/Wataaaame', tip: 'Wataaaame' }
    # - { class: 'iconfont icon-douban-fill', link: 'https://douban.com', tip: '豆瓣' }
    - { class: 'iconfont icon-wechat-fill', qrcode: '/images/image-info/weChat.JPG' }
